%% Parameters
variables = struct(...
    'domain',           {{'column', 'spire', 'twobar'}}, ...
    'helem',            {{0.50}}, ...
    'nevals',           {{6.00}}, ...
    'sf',               {{2.00, 2.50, 3.00, 3.50, 4.00}}, ...
    'minloop',          {{350}}, ...
    'maxloop',          {{400}}, ...
    'pphysstart',       {{2}}, ...
    'pphysend',         {{6}}, ...
    'dpphys',           {{0.25}}, ...
    'pNstart',          {{8}}, ...
    'pNend',            {{32}}, ...
    'betastart',        {{6}}, ...
    'betaend',          {{6}}, ...
    'contstart',        {{30}}, ...
    'NBASIS_STAT',      {{8}}, ...
    'NBASIS_EIGS',      {{4}}, ...
    'NBASIS_ADJT',      {{8}}, ...
    'CA_START',         {{2}}, ...
    'CHOL_UPDATE_PACE', {{10}}, ...
    'CA_ANG_TOL',       {{1-5e-4}}, ...
    'CAorthotype',      {{'current', 'old'}}, ...
    'SHOW_DESIGN',      {{1}}, ...
    'mpara',            {{[2e-1, 2e5, 0.30]}}, ...
    'rmin',             {{3.00}}, ...
    'xi',               {{1}}, ...
    'x0strat',          {{'homg', 'comp'}});

jobdir = 'src/simulate';
jobname = 'minCstVBLF.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'rom';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);
