%% Parameters
variables = struct(...
    'domain',           {{'column', 'spire', 'twobar'}}, ...
    'helem',            {{1.50}}, ...
    'nevals',           {{4.00}}, ...
    'sf',               {{1.10}}, ...
    'minloop',          {{20}}, ...
    'maxloop',          {{30}}, ...
    'pphysstart',       {{2}}, ...
    'pphysend',         {{6}}, ...
    'dpphys',           {{0.50}}, ...
    'contpace',         {{5}}, ...
    'contstart',        {{5}}, ...
    'pNstart',          {{8}}, ...
    'pNend',            {{9}}, ...
    'dpN',              {{1}}, ...
    'betastart',        {{6}}, ...
    'betaend',          {{8}}, ...
    'dbeta',            {{0.50}}, ...
    'betapace',         {{4}}, ...
    'NBASIS_STAT',      {{6}}, ...
    'NBASIS_EIGS',      {{3}}, ...
    'NBASIS_ADJT',      {{6}}, ...
    'CA_START',         {{2}}, ...
    'CHOL_UPDATE_PACE', {{10}}, ...
    'CA_ANG_TOL',       {{1-100e-4}}, ...
    'CAorthotype',      {{'old'}}, ...
    'SHOW_DESIGN',      {{1}}, ...
    'mpara',            {{[2e-1, 2e5, 0.30]}}, ...
    'rmin',             {{6.00}}, ...
    'xi',               {{1}}, ...
    'x0strat',          {{'homg'}}, ... % IMPORTANT FOR TEST AS COMP MIGHT NOT EXIST
    'mmalen',           {{0.100}}, ...
    'PROFILE',          {{true}}, ...
    'SAVEX',            {{true}});

jobdir = 'src/simulate';
jobname = 'minCstVBLF.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'test';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);
