%% Parameters
variables = struct(...
    'domain', {{'column', 'spire', 'twobar'}}, ...
    'nevals', {{6}}, ...
    'helem', {{0.5}}, ...
    'sf', {{2.50}}, ...
    'rmin', {{3.00}}, ...
    'NBASIS_STAT', {{6}}, ...
    'NBASIS_EIGS', {{3}}, ...
    'NBASIS_ADJT', {{6}}, ...
    'CA_START', {{10}}, ...
    'CHOL_UPDATE_PACE', {{10}}, ...
    'CA_CHANGE_TOL', {{0.200}}, ...
    'SHOW_DESIGNS', {{1}});
jobdir = 'src/simulate';
jobname = 'minCstVBLF.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'rom';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);