%% Parameters
variables = struct(...
    'domain', {{'column', 'spire', 'twobar'}}, ...
    'nevals', {{6}}, ...
    'helem', {{0.5}}, ...
    'sf', {{2.50, 3.50, 4.50}}, ...
    'rmin', {{3.00}}, ...
    'NBASIS_STAT', {{nan}}, ...
    'NBASIS_EIGS', {{nan}}, ...
    'NBASIS_ADJT', {{nan}}, ...
    'CA_START', {{inf}}, ...
    'CHOL_UPDATE_PACE', {{nan}}, ...
    'CA_ANG_TOL', {{0.200}}, ...
    'SHOW_DESIGN', {{1}});

jobdir = 'src/simulate';
jobname = 'minCstVBLF.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'ref';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);