%% Parameters
variables = struct(...
    'domain', {{'column', 'spire', 'twobar'}}, ...
    'nevals', {{6}}, ...
    'helem', {{0.5}}, ...
    'rmin', {{3.00}});

jobdir = 'src/simulate';
jobname = 'minCstV.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'compref';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);