%% Parameters
variables = struct(...
    'domain', {{'column', 'spire', 'twobar'}}, ...
    'helem', {{0.5}}, ...
    'f', {{2.00, 2.50}}, ...
    'rmin', {{2.00, 3.00}}, ...
    'NBASIS_STAT', {{6}}, ...
    'NBASIS_EIGS', {{3}}, ...
    'NBASIS_ADJT', {{6}}, ...
    'CA_START', {{10}}, ...
    'CHOL_UPDATE_PACE', {{10}}, ...
    'CA_CHANGE_TOL', {{0.200}}, ...
    'filename', {{'results.mat'}});
jobdir = 'src/simulate';
jobname = 'minCstVBLF_study.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'rom';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);