%% Parameters
test = 0;
if test
    variables = struct(...
        'NBASIS_STAT', {{6}}, ...
        'NBASIS_EIGS', {{4}}, ...
        'NBASIS_ADJT', {{6}}, ...
        'CA_START', {{5}}, ...
        'CHOL_UPDATE_PACE', {{1}}, ...
        'domain', {{'column'}}, ...
        'helem', {{2}}, ...
        'filename', {{'results.mat'}});
else
    variables = struct(...
        'NBASIS_STAT', {{6}}, ...
        'NBASIS_EIGS', {{3}}, ...
        'NBASIS_ADJT', {{6}}, ...
        'CA_START', {{5}}, ...
        'CHOL_UPDATE_PACE', {{10}}, ...
        'domain', {{'column', 'spire', 'twobar'}}, ...
        'helem', {{1}}, ..., ...
        'filename', {{'results.mat'}});
end
jobdir = 'src/simulate';
jobname = 'minCstVBLF_study.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'buckling_study';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);