%% Parameters
test = 0;
if test
    variables = struct(...
        'NBASIS_STAT', {{6}}, ...
        'NBASIS_EIGS', {{4}}, ...
        'NBASIS_ADJT', {{6}}, ...
        'CA_START', {{inf}}, ...
        'CHOL_UPDATE_PACE', {{1}}, ...
        'domain', {{'column'}}, ...
        'helem', {{2}}, ...
        'f', {{1.0, 1.5, 2.0, 2.5}}, ...
        'filename', {{'results.mat'}});
else
    variables = struct(...
        'NBASIS_STAT', {{nan}}, ...
        'NBASIS_EIGS', {{nan}}, ...
        'NBASIS_ADJT', {{nan}}, ...
        'CA_START', {{inf}}, ...
        'CHOL_UPDATE_PACE', {{nan}}, ...
        'domain', {{'column', 'spire', 'twobar'}}, ...
        'helem', {{1}}, ...
        'f', {{1.0, 1.5, 2.0, 2.5}}, ...
        'filename', {{'results.mat'}});
end
jobdir = 'src/simulate';
jobname = 'minCstVBLF_study.m';
jobfarmParentdir = 'processed_data';
jobfarmdirNamebase = 'buckling_study_reference';
generate_jobs(jobdir, jobname, jobfarmParentdir, jobfarmdirNamebase, variables);